## Generating 1d array.

In [2]:
import numpy as np

random_integers = np.random.randint(1,101, size=10)
print(random_integers)

[89 69 28 53 42 19 39 14 24  7]


### Acessing first and last elements in the array.

In [3]:
first_element = random_integers[0]
last_element = random_integers[-1]
print(first_element)
print(last_element)

89
7


## Generating the 2d array

In [4]:
random_floats_2d = np.random.rand(3, 3)
print(random_floats_2d)

[[0.45080111 0.05231764 0.64813671]
 [0.6517985  0.76878944 0.10660286]
 [0.41479318 0.37219299 0.97579048]]


## Accessing the first row and last column

In [8]:
first_row = random_floats_2d[0]
print(first_row)

[0.45080111 0.05231764 0.64813671]


In [10]:
last_column = random_floats_2d[:, -1]
print(last_column)

[0.64813671 0.10660286 0.97579048]


# Accessing the sub_array

In [11]:
# Assuming random_floats_2d is your 2D array
sub_array = random_floats_2d[:2, :2]
print(sub_array)

[[0.45080111 0.05231764]
 [0.6517985  0.76878944]]


## Doing the addition multiplication and square operations.

In [12]:
import numpy as np

# Generate two 1D NumPy arrays of 5 random integers each
array1 = np.random.randint(1, 101, size=5)
array2 = np.random.randint(1, 101, size=5)

# a. Add the two arrays and print the result
added_arrays = array1 + array2
print("Added arrays:", added_arrays)

# b. Multiply the two arrays (element-wise) and print the result
multiplied_arrays = array1 * array2
print("Multiplied arrays (element-wise):", multiplied_arrays)

# c. Calculate the square of every element in the first array and print it
squared_array1 = array1 ** 2
print("Square of every element in the first array:", squared_array1)


Added arrays: [118 145  95 108 111]
Multiplied arrays (element-wise): [3445 4704 1836 2291 1598]
Square of every element in the first array: [2809 2401 4624  841  289]
