In [1]:
import numpy as np
import pandas as pd
from statistics import mode
import random


random_numbers = [random.randint(1, 50) for _ in range(20)]
print(random_numbers)

mean_val = np.mean(random_numbers)
median_val = np.mean(random_numbers)

get_mode = lambda x: mode(x)
mode_value = get_mode(random_numbers)

variance = np.var(random_numbers)
std_deviation = np.std(random_numbers)
print(mean_val)
print(median_val)
print(mode_value)
print(variance)
print(std_deviation)


[32, 16, 47, 41, 47, 12, 41, 2, 45, 16, 9, 29, 5, 39, 41, 18, 21, 27, 44, 37]
28.45
28.45
41
212.4475
14.575578890733636


In [ ]:
mean_age = df['age'].mean()
df['age'].fillna(mean_age, inplace = True)


In [ ]:
median_income = df['income'].median()
##percentiles_petal_length = iris['petal_length'].quantile([0.25, 0.5, 0.75])
#print("25th percentile of 'petal_length':", percentiles_petal_length[0.25])
#print("50th percentile (median) of 'petal_length':", percentiles_petal_length[0.5])
#print("75th percentile of 'petal_length':", percentiles_petal_length[0.75])
#percentile_25 = np.percentile(unit_prices, 25)
#percentile_50 = np.percentile(unit_prices, 50)
#percentile_75 = np.percentile(unit_prices, 75)

#print("25th Percentile:", percentile_25)
#print("50th Percentile:", percentile_50)
#print("75th Percentile:", percentile_75)

In [2]:
A = np.random.randint(1,11,size =(8,8))
B = np.random.randint(1,11,size = (8,8))
print(A)
print(B)

[[ 4  7  1  3  3  8 10  5]
 [ 6  4  3  8  8  2  1 10]
 [10  3  9  4  6 10  7  2]
 [ 1 10  7  8  9  8  2  5]
 [ 8  7  4  2  9  8  2  1]
 [ 4  4  1  1  3  1  7  5]
 [ 5  8  6  4  8 10  2  6]
 [10  6  4 10  9  3  4  7]]
[[ 7 10  4  4  3  8  7  6]
 [ 5  6 10  5  6  1 10  7]
 [ 3  8  6  7  5  5  9  1]
 [ 1  7  9  1  3  5  8  1]
 [ 5 10  4  1  2  4  3  3]
 [ 9 10  8  6  2  2  8  8]
 [ 3  1  2  7  4  5  6  4]
 [ 8  7 10  7 10  2  2  7]]


In [3]:
AB = np.dot(A,B)
print(AB)

[[226 266 265 217 180 147 274 225]
 [220 335 304 170 205 168 239 189]
 [273 399 298 251 185 231 357 234]
 [249 389 372 217 214 165 347 225]
 [236 347 258 175 144 165 283 209]
 [137 161 155 137 130 105 154 134]
 [281 398 348 230 209 172 329 250]
 [262 411 352 212 226 232 335 232]]


In [5]:
AB_inv = np.linalg.inv(AB)
print(AB_inv)

[[-0.51645749 -1.55861031 -0.34020053 -0.8521381  -1.17726501  0.12078317
   2.22385047  1.5345651 ]
 [ 0.18576332  0.63799741  0.14132461  0.35027043  0.49004572 -0.02810525
  -0.89839286 -0.63928577]
 [ 0.07648036  0.11112188  0.02813931  0.03114964  0.03708802 -0.08176341
  -0.12196356 -0.07804996]
 [ 0.22773963  0.66579769  0.16688163  0.34115824  0.45939306 -0.07809867
  -0.90594891 -0.65495167]
 [-0.1706562  -0.37911766 -0.09563398 -0.16779319 -0.2449494   0.11644554
   0.50035898  0.34777448]
 [ 0.03549692  0.03307961  0.01243451 -0.00611879  0.00306365 -0.04104576
  -0.03946259 -0.00451003]
 [-0.20534791 -0.57837148 -0.13070529 -0.27399987 -0.39580566  0.0850314
   0.76852032  0.54719653]
 [ 0.35726646  1.02429104  0.20809883  0.5480155   0.79237509 -0.08636161
  -1.46464281 -1.00365434]]


In [6]:
BA_inv = np.dot(np.linalg.inv(A),np.linalg.inv(B))
print(BA_inv)

[[ 1.22902098e-02  6.79065404e-02 -5.77237563e-02 -7.26953829e-05
   2.21917128e-02 -2.61578420e-02  3.69174986e-02 -3.76412339e-02]
 [-2.94925933e-02  6.67931426e-02 -9.26804915e-02  1.27345238e-02
   6.56684511e-02 -1.78700936e-02  1.19119184e-01 -6.15424501e-02]
 [-2.80566986e-01 -1.00877426e-02 -1.40444748e-01  8.20238743e-02
   3.18834539e-01  2.54995127e-02  3.03118027e-01 -6.95214925e-02]
 [-7.94077232e-02  4.59674089e-04 -2.89431023e-02 -5.13749580e-03
   8.31007848e-02  2.37938198e-02  5.86666754e-02 -1.00222606e-02]
 [-6.51197075e-02 -7.29590404e-02  7.61382079e-02 -1.54130932e-02
   7.01892507e-02 -1.02628635e-02 -2.14432537e-02  5.98523241e-02]
 [ 2.86501040e-01 -2.72419253e-03  1.43921611e-01 -5.81423336e-02
  -3.63167916e-01  1.66037430e-03 -3.14689005e-01  6.40350724e-02]
 [ 7.82072088e-03 -6.82659617e-02  2.74316308e-02  1.87218822e-02
  -3.98962057e-02  2.34785468e-02 -2.95046668e-02  4.22029044e-02]
 [ 7.19003750e-02  8.34131810e-03  2.53710452e-02 -4.03179040e-03
  -

In [9]:
are_equal = np.allclose(AB_inv, BA_inv)
if(are_equal):
    print("\n(A * B)^-1 is equal to B^-1 * A^-1:", are_equal)
else:
  print("not equal")

not equal
